---
title: "HW 2"
author: "Aislinn Gilmour"
date: "2025-10-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries
```{r, message=FALSE, warning=FALSE}
library(tidyr)
library(dplyr)
library(Seurat)
library(ggplot2)
library(clustree)
```

Load in Data from Geo
```{r , message=FALSE, warning=FALSE}
#untar data from GEO
untar("GSE155224_RAW.tar", exdir = "geo_data")

#unzip the cell ranger files
#NOTE- i used Chat GPT to help write this loop because I couldn't get the data to 
#load in correctly and I couldn't find any examples online doing it in a loop 
for (f in list.files("geo_data", pattern = "cellranger\\.tar\\.gz$", full.names = TRUE,
                     recursive = TRUE)) {
  outdir <- file.path("geo_data", "unzipped", sub("\\.tar.*$", "", basename(f)))
  dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
  untar(f, exdir = outdir)
}
```

Get Files and Sample Names
```{r, message=FALSE, warning=FALSE}
# Note: I also used Chat GPT to use the right RegEx for this section to reference the correct file paths

files <- list.files(
  "geo_data/unzipped",
  pattern = "filtered_feature_bc_matrix$",
  recursive = TRUE,
  full.names = TRUE,
  include.dirs = TRUE
)

# Skip CITE files
files <- files[!grepl("CITE", files, ignore.case = TRUE)]

inner   <- basename(dirname(dirname(files)))
samples <- sub("_.*$", "", inner)

```

Load in Data
```{r}
for(i in 1:length(samples)){
 sample = samples[i]
 file = files[i]
 print(sample)
 td = Read10X(file)
 t = CreateSeuratObject(counts = td, project=sample)
 if(sample == samples[1]){
 obj = t
 }else{
 obj = merge(obj, t)
 }
}
```

Set up Patient Cohorts
```{r}
obj@meta.data$cohort = "COVID-19"
obj@meta.data$cohort[nchar(obj@meta.data$orig.ident) == 10] = "Healthy"
```

```{r}

```







